server:
  port: 8080
  servlet:
    context-path: /project

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/project"
    username: root
    password: 1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.springframework.security: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
jwt:
  signerKey: "TsYkPH4h8YN2VmA56ju2B1yX55j8ANAFUrC+GYaDmipJDCFIo37Pc+ERE66I8rVS"
  valid-duration: 120 # in seconds
  refreshable-duration: 120 # in seconds